# Generated by Django 2.2.17 on 2020-12-08 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('etest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etest.Etest')),
            ],
        ),
    ]
