# Generated by Django 3.1.3 on 2021-02-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgespace',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
