# Generated by Django 3.1.3 on 2021-01-12 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etest', '0002_course_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgespace',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_spaces', to='etest.domain'),
        ),
    ]
