# Generated by Django 3.1.4 on 2020-12-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etest', '0002_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('answers', models.ManyToManyField(to='etest.Answer')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
            },
        ),
    ]
