# Generated by Django 3.1.4 on 2021-01-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etest', '0002_answer_question_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
