# Generated by Django 3.1.3 on 2021-02-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etest', '0003_link_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgespace',
            name='ged',
            field=models.IntegerField(default=0),
        ),
    ]
