# Generated by Django 2.2.17 on 2020-12-08 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etest', '0004_testtaker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UsersAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='etest.Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etest.Question')),
                ('test_taker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etest.TestTaker')),
            ],
        ),
    ]
